---
build_from:
  aarch64: ghcr.io/hassio-addons/base:19.0.0
  amd64: ghcr.io/hassio-addons/base:19.0.0
  armv7: ghcr.io/hassio-addons/base:19.0.0
codenotary:
  base_image: codenotary@frenck.dev
  signer: ghoozh@gmail.com
